# name: Build and Deploy to GCP

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@master
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: ${{ secrets.GCP_PROJECT }}
#           export_default_credentials: true

#       - name: Authenticate Docker
#         run: |
#           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#       - name: Build Docker Image
#         run: |
#           docker build -t gcp-deploy .

#       - name: Push Docker Image
#         run: |
#           # Replace YOUR_REGISTRY with your registry name and YOUR_IMAGE_NAME with your image's name
#           docker tag gcp-deploy:latest YOUR_REGISTRY/YOUR_IMAGE_NAME:latest
#           docker push YOUR_REGISTRY/YOUR_IMAGE_NAME:latest

#       - name: Deploy to GCP
#         run: |
#           # Replace YOUR_REGISTRY and YOUR_IMAGE_NAME with your registry and image names
#           gcloud run deploy YOUR_SERVICE_NAME --image YOUR_REGISTRY/YOUR_IMAGE_NAME:latest --platform managed
